### ISSUE TITLE
c++ code on windows?

### ISSUE THREAD

**Issue by antithing** [donglao/videoinpainting#3]
Hi, thank you for this great work. Will it be possible to run the c++ code on Windows? Ideally without Matlab!

Thanks

**Comment by donglao** [comment]
Hi,

Thanks for your interest in this work. The C++ code takes care of optical
flow calculations and refinement, which is from 'Shape Tracking with
Occlusions via Coarse-to-Fine Region-Based Sobolev Descent, PAMI 2015'.
This piece of the code is no longer updated. I have tried to configure the
code for Windows but had no luck.

**Comment by antithing** [comment]
Understood. Thank you for getting back to me.
